rails_app/config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  root to: "home#index"
  # ...

  resources :announcements, only: [:index]
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks"}
  post '/', to: "home#enqueue"
end

rails_app/app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id                :bigint           not null, primary key
#  announcement_type :string
#  description       :text
#  name              :string
#  published_at      :datetime
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Announcement < ApplicationRecord
  TYPES = %w[new fix update]

  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  # validations ...............................................................
  validates :announcement_type, :description, :name, :published_at, presence: true
  validates :announcement_type, inclusion: {in: TYPES}

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  after_initialize :set_defaults

  # class methods .............................................................
  # class << self
  # end

  # public instance methods ...................................................
  def set_defaults
    self.published_at ||= Time.zone.now
    self.announcement_type ||= TYPES.first
  end

  # protected instance methods ................................................
  protected

  # private instance methods ..................................................
  private
end

rails_app/app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :mark_as_read, if: :user_signed_in?

  def index
    @announcements = Announcement.order(published_at: :desc)
  end

  private

  def mark_as_read
    current_user.update(announcements_last_read_at: Time.zone.now)
  end
end

rails_app/app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def unread_announcements(user)
    last_announcement = Announcement.order(published_at: :desc).first
    return if last_announcement.nil?

    # Highlight announcements for anyone not logged in, cuz tempting
    if user.nil? || user.announcements_last_read_at.nil? || user.announcements_last_read_at < last_announcement.published_at
      "unread-announcements"
    end
  end

  def announcement_class(type)
    {
      "new" => "text-success",
      "update" => "text-warning",
      "fix" => "text-danger"
    }.fetch(type, "text-success")
  end
end

rails_app/app/views/announcements/index.html.erb
<h1>What's New</h1>
<% @announcements.each_with_index do |announcement, index| %>
  <% if index != 0 %>
    <div>
      <div>
        <hr>
      </div>
    </div>
  <% end %>
  <div id="<%= dom_id(announcement) %>">
    <div>
      <%= link_to announcements_path(anchor: dom_id(announcement)) do %>
        <strong><%= announcement.published_at.strftime("%b %d") %></strong>
      <% end %>
    </div>
    <div>
      <strong class="<%= announcement_class(announcement.announcement_type) %>"><%= announcement.announcement_type.titleize %>:</strong>
      <strong><%= announcement.name %></strong>
      <%= simple_format announcement.description %>
    </div>
  </div>
<% end %>
<% if @announcements.empty? %>
  <div>Exciting stuff coming very soon!</div>
<% end %>